import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Geist } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "SmartCamp",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} font-sans antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Header />
					<div className="w-full max-w-screen-xl mx-auto px-2">{children}</div>
					<Toaster richColors />
				</ThemeProvider>
			</body>
		</html>
	);
}
